<a href="https://colab.research.google.com/github/shantanuchanekar/Excelr/blob/main/Normal_Distribution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from scipy import stats

In [ ]:
1-stats.norm.cdf(720,711,29)

0.37814937265194704

In [ ]:
1-stats.norm.cdf(60,50,5)

0.02275013194817921

In [3]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [4]:
from google.colab import files
uploaded = files.upload()

Saving BEML.csv to BEML.csv
Saving GLAXO.csv to GLAXO.csv

In [55]:
beml_df = pd.read_csv('BEML.csv')
beml_df.head()

,Date,Open,High,Low,Last,Close,Total Trade Quantity,Turnover (Lacs)
0,2010-01-04,1121.0,1151.00,1121.00,1134.0,1135.60,101651.0,1157.18
1,2010-01-05,1146.8,1149.00,1128.75,1135.0,1134.60,59504.0,676.47
2,2010-01-06,1140.0,1164.25,1130.05,1137.0,1139.60,128908.0,1482.84
3,2010-01-07,1142.0,1159.40,1119.20,1141.0,1144.15,117871.0,1352.98
4,2010-01-08,1156.0,1172.00,1140.00,1141.2,1144.05,170063.0,1971.42

In [54]:
gl_df = pd.read_csv('GLAXO.csv')
gl_df.head()

,Date,Open,High,Low,Last,Close,Total Trade Quantity,Turnover (Lacs)
0,2010-01-04,1613.00,1629.10,1602.00,1629.0,1625.65,9365.0,151.74
1,2010-01-05,1639.95,1639.95,1611.05,1620.0,1616.80,38148.0,622.58
2,2010-01-06,1618.00,1644.00,1617.00,1639.0,1638.50,36519.0,595.09
3,2010-01-07,1645.00,1654.00,1636.00,1648.0,1648.70,12809.0,211.00
4,2010-01-08,1650.00,1650.00,1626.55,1640.0,1639.80,28035.0,459.11

In [56]:
gl_df = gl_df[['Date','Close']]
beml_df = beml_df[['Date','Close']]

In [57]:
gl_df.head()

         Date    Close
0  2010-01-04  1625.65
1  2010-01-05  1616.80
2  2010-01-06  1638.50
3  2010-01-07  1648.70
4  2010-01-08  1639.80

In [58]:
beml_df.head()

         Date    Close
0  2010-01-04  1135.60
1  2010-01-05  1134.60
2  2010-01-06  1139.60
3  2010-01-07  1144.15
4  2010-01-08  1144.05

In [59]:
beml_df['Date'] = pd.to_datetime(beml_df['Date'])
beml_df.dtypes

Date     datetime64[ns]
Close           float64
dtype: object

In [60]:
gl_df = gl_df.set_index(pd.DatetimeIndex(gl_df['Date'])).drop('Date',axis=1)
beml_df = beml_df.set_index(pd.DatetimeIndex(beml_df['Date'])).drop('Date',axis=1)

In [61]:
gl_df.head()

              Close
Date
2010-01-04  1625.65
2010-01-05  1616.80
2010-01-06  1638.50
2010-01-07  1648.70
2010-01-08  1639.80

In [62]:
beml_df.head()

              Close
Date
2010-01-04  1135.60
2010-01-05  1134.60
2010-01-06  1139.60
2010-01-07  1144.15
2010-01-08  1144.05

In [63]:
beml_df.dtypes

Close    float64
dtype: object